spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rip'
    username: 'postgres'
    password: 'postgres'
  rabbitmq:
    username: 'admin'
    password: 'admin'
    virtual-host: 'vhost'
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

